# Tutorial de Python

![Python](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/200px-Python-logo-notext.svg.png)

[**Python**](https://es.wikipedia.org/wiki/Python) es un lenguaje de programación interpretado cuya filosofía hace hincapié en la legibilidad de su código.​ Se trata de un lenguaje de programación multiparadigma, ya que soporta orientación a objetos, programación imperativa y, en menor medida, programación funcional. Es un **lenguaje interpretado**, **dinámico** y **multiplataforma**.

En este tutorial se asume que tenés experiencia en otros lenguajes de programación. A continuación te dejo una lista de recursos que podes  consultar si tenés más curiosidad sobre Python.

- [Python](https://es.wikipedia.org/wiki/Python) en la Wikipedia.
- [Python Tutorial With Google Colab](https://colab.research.google.com/github/cs231n/cs231n.github.io/blob/master/python-colab.ipynb#scrollTo=dzNng6vCL9eP) del curso *Convolutional Neural Networks for Visual Recognition* de *Stanford University*.
- [Tutorial de Python](https://docs.python.org/es/3/tutorial/index.html) oficial (en español).
 
---

Por último antes de empezar, si notas que el notebook tiene algún error no dejes de avisarnos! Muchas gracias y que disfrutes el tutorial.

## Variables y operaciones

Las variables son como contenedores (u objetos), esto quiere decir que además tienen sus propios métodos. Al ser de tipado dinámico, el tipo de datos de la variable se infiere durante la declaración de la misma:

### Números

In [1]:
num = 3
print(type(num)) # type
print(num)
print(num + 1)
print(num - 1)
print(num * 2)
print(num ** 2) # exp
num += 1
print(num)  # Prints '4'
num *= 2
print(num)  # Prints '8'
numFloat = 2.5
print(type(numFloat))
print(numFloat, numFloat + 1, numFloat * 2, numFloat ** 2)

<class 'int'>
3
4
2
6
9
4
8
<class 'float'>
2.5 3.5 5.0 6.25


### Texto

In [2]:
texto1 = 'hola'
texto2 = "mundo"
print(texto1)
print(len(texto1)) # ammount of chars
mensaje = texto1 + ' ' + texto2
print(mensaje)
mensaje = '%s %s %d' % (texto1, texto2, 123)
print(mensaje)

print(texto1.capitalize()) # Capitalize a string; prints 'Hola'
print(texto1.upper()) # Convert a string to uppercase; prints 'HOLA'

hola
4
hola mundo
hola mundo 123
Hola
HOLA


### Operaciones

No pueden combinarse tipos de datos, salvo que sea posible una conversión por parte del intérprete. Por ejemplo, un entero puede convertirse a `float`.

In [3]:
sum = num + numFloat
print(sum)

xString = '10'
sumString = xString + xString
print(sumString)

# The following operation will throw an error (string + integer)
"""
sum = xString + num 
print(sum)
"""
# You can try to run it, if you want

try:
  sum = xString + num
  print(sum)
except:
  print('Exception!')

10.5
1010
Exception!


Python es **case sensitive**, lo que quiere decir que diferencia variables según letras minúsculas y mayúsculas.

###Booleanos

Para las operaciones lógicas se utiliza `and`, `or`, y `not` junto con los operadores básicos de comparación `<`, `>`, `>=`, etc.


In [4]:
booleanTrue = True # Note the uppercase
booleanFalse = False

print(booleanTrue)

print(booleanTrue and booleanFalse)
print(booleanTrue or booleanFalse)
print(not booleanFalse)

print('Now... conditionals!')
print(9 < 11)
print(4 != 4)
print("string" == 'string')
print(3 < 4 and 4 < 3)

True
False
True
True
Now... conditionals!
True
False
True
False


###Listas

Las listas son un tipo predefinido del lenguaje. Se acceden mediante corchetes `[ ]` indicando el índice de la posición.

In [5]:
listaVacia = []
print(listaVacia)

lista = [1, 2, 3]
print(lista)

lista = ['string', 'hola', 'chau', 'casa']
print(lista)

print(lista[1]) # Indices start at zero
print(lista[-1])
print(lista[0:2])

[]
[1, 2, 3]
['string', 'hola', 'chau', 'casa']
hola
casa
['string', 'hola']


##Estructuras de control

En los lenguajes de programación, las estructuras de control permiten modificar el flujo de ejecución de las instrucciones de un programa. Las más conocidas son *IF-THEN-ELSE*, *FOR-NEXT*, y *DO-WHILE*. En Python cada una tiene su sintaxis específica que vamos a revisar a continuación.

**IMPORTANTE**: En Python no se utilizan las llaves `{ }` para marcar bloques de código, sino que **se hace mediante indentaciones**. Para utilizar sentencias de control como por ejemplo el *if* es necesario indentar. Por defecto, son 4 espacios (un tab).


### IF-THEN-ELSE

De acuerdo con una condición permite ejecutar un grupo u otro de sentencias. En Python su sintaxis es la siguiente:

```
if CONDICION:
  codigo (indentado)  
else:
  codigo (indentado)
```

A continuación puede ejecutar una celda y modificar los valores de las variables y/o la condición para evaluar su funcionamiento.

In [6]:
totalPago = 300
clientePorMayor = True
comproProductoPrincipal = True

if totalPago > 250 and clientePorMayor:
  print('Ha ganado un descuento por compra mayor y cliente')
elif comproProductoPrincipal:
  print('Ha ganado descuento por comprar el producto principal')
else:
  print('Gracias por su compra')

Ha ganado un descuento por compra mayor y cliente


## Estructuras iterativas



### FOR-NEXT

Permite ejecutar un grupo de sentencias un número determinado de veces. En Python su sintaxis es la siguiente:

```
for VARIABLE in LISTA:
  codigo (identando)
```

A continuación puede ejecutar la celda y modificar los valores de las variables para evaluar su funcionamiento.

In [7]:
lista = [1, 2, 3, 4, 5]
for elemento in lista:
  print(elemento)

for elemento in lista:
  if elemento % 2 == 0:
    print(f'Nro par encontrado, {elemento}')
  else:
    print(f'Nro impar encontrado, {elemento}')

1
2
3
4
5
Nro impar encontrado, 1
Nro par encontrado, 2
Nro impar encontrado, 3
Nro par encontrado, 4
Nro impar encontrado, 5


### DO-WHILE

Ejecutar un grupo de sentencias solo mientras de forma iterativa se cumpla una condición. En Python su sintaxis es la siguiente:

```
while condicion:
  codigo (identado)
```

A continuación puede ejecutar la celda y modificar los valores de las variables para evaluar su funcionamiento.

In [8]:
numero = 1
while numero > 0 and numero < 7:
  print(numero)
  numero += 1

1
2
3
4
5
6


## Funciones

Se definen con la palabra reservada del lenguaje `def`.

La sintaxis es:

```
def nombre_func(params)
  codigo (identado)
```

Y para devolver un resultado utilizamos `return`.

Algo interesante es que podemos devolver varios resultados de distinto tipo.



In [9]:
def sumar(a, b):
  resultado = a + b
  if(resultado > 50):
    return resultado, '> 50'
  else:
    return resultado, '<= 50'

res, detalle = sumar(10, 19)
print(f'Resultado {res} | Detalle {detalle}')

Resultado 29 | Detalle <= 50


### Importaciones de módulos

Para importar paquetes se usa la palabra reservada `import`.

Por ejemplo, `numpy`. El cual es uno de los paquetes fundamentales utilizados para cálculo computacional en Python. Permite entre otras cosas:

*   Crear matrices
*   Integración con C/C++
*   Operaciones de álgebra lineal, transformada de Fourier, etc.

Si indicamos el `from`, especificamos el repositorio / origen del paquete.

```
from repository import method 
a = method()
```

```
import repository.method
a = repository.method()
```

En otras palabras, si sólo usamos `import`, se crea una referencia al módulo `X`, y para acceder a los métodos contenidos en `X` debemos hacer `X.metodo()`.

En cambio, si usamos `from`, podemos acceder directamente a los métodos.

In [10]:
import numpy as np

array = np.arange(9).reshape(3, 3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## NumPy

NumPy es una biblioteca para el lenguaje de programación Python que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas. La funcionalidad principal de NumPy es su estructura de datos `ndarray` para crear matrices de *n* dimensiones.

Esta es una descripción general y muy rápida de las matrices en Numpy. Se recomienda leer el artículo [NumPy Quickstart](https://numpy.org/doc/stable/user/quickstart.html) disponible en la documentación oficial de la librería para profundizar en estos conceptos.

### `ndarrays`

A diferencia de la estructura de datos de lista incorporada de Python, estas matrices se escriben de forma homogénea: **todos los elementos de una única matriz deben ser del mismo tipo**.

La función `shape` de un arreglo nos devuelve una tupla de enteros, representando el tamaño de cada dimensión del arreglo.

In [11]:
# Ejemplo de Arreglo
print('Arreglo (1D)')
array = np.array([1, 2, 3]) # Creamos el arreglo
print(type(array))
print(array.shape)
print(array[0], array[1], array[2])
array[0] = 5
print(array, '\n')

# Ejemplo de Matriz
print('Matriz (2D)')
array = np.array([[1, 2, 3], [4, 5, 6]]) # Creamos la matriz
print(array.shape)
print(array)
print(array[0, 0], array[0, 1], array[1, 0], '\n')

# Ejemplo de 3 Dimensiones
print('3D')
array = np.array([
                  [[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]],
                  [[13, 14, 15],[16, 17, 18]]
                  ])
print(array.shape)
print(array)
print(array[0, 0, 0], array[0, 1, 0], array[1, 0, 0], '\n')

print('Deben ser del mismo tipo...')
array = np.array([['a', 'b', 'c', 10], [5, 6, 7, 8]])
print(array)
print(array[0, 2] + array[0, 3])

Arreglo (1D)
<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3] 

Matriz (2D)
(2, 3)
[[1 2 3]
 [4 5 6]]
1 2 4 

3D
(3, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
1 4 7 

Deben ser del mismo tipo...
[['a' 'b' 'c' '10']
 ['5' '6' '7' '8']]
c10


### Indexando `ndarrays`

Esta es una descripción general y muy rápida de las matrices en Numpy. Se recomienda leer el artículo [indexing](https://numpy.org/doc/stable/reference/arrays.indexing.html) disponible en la documentación oficial de la librería para profundizar en estos conceptos.

Los ndarrays se pueden indexar usando la sintaxis estándar de Python, `x[obj]`, donde `x` es la matriz y `obj` la *selección*.

In [12]:
print('Creando un array de 2 dimensiones a partir de una secuencia de números...')
array = np.arange(25).reshape(5,5) # Creamos una matriz de tamaño 5x5 con números del 0 al 24
print(array, '\n')

print('Extrayendo los elementos de filas y columnas del array 2D...') 
subArray = array[:2, :2] # de la 1er fila a la 2da fila, de la 1er columna a la 2da columna
print(subArray, '\n')

subArray = array[1:4, 1:4] # de la 2da fila a la 4ta fila, de la 2da columna a la 4ta columna
print(subArray, '\n')

print('Remplazando un bloque de elementos del array por otro bloque del mismo tamaño')
newArray = np.zeros((3, 3)) # Creamos matriz de ceros
print(newArray, '\n')

array[1:4, 1:4] = newArray 
print(array, '\n')

Creando un array de 2 dimensiones a partir de una secuencia de números...
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

Extrayendo los elementos de filas y columnas del array 2D...
[[0 1]
 [5 6]] 

[[ 6  7  8]
 [11 12 13]
 [16 17 18]] 

Remplazando un bloque de elementos del array por otro bloque del mismo tamaño
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[ 0  1  2  3  4]
 [ 5  0  0  0  9]
 [10  0  0  0 14]
 [15  0  0  0 19]
 [20 21 22 23 24]] 



--- 

# THE END

Y llegamos al final de este tutorial! Cualquier comentario no dudes en escribirme.

**Saludos y gracias por tu tiempo!!**